In [ ]:
!pip install kss
!apt-get -qq install mecab libmecab-dev mecab-ko mecab-ko-dic
!pip install mecab-python3
!pip install imbalanced-learn
!pip install -U sentence-transformers
!pip install imblearn
!pip install pyarrow

Collecting kss
  Downloading kss-6.0.4.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting emoji==1.2.0 (from kss)
  Downloading emoji-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting pecab (from kss)
  Downloading pecab-1.0.8.tar.gz (26.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 55.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from kss) (3.5)
Collecting jamo (from kss)
  Downloading jamo-0.4.1-py3-none-any.whl.metadata (2.3 kB)
Collecting hangul-jamo (from kss)
  Downloading hangul_jamo-1.0.1-py3-none-any.whl.metadata (899 bytes)
Collecting tossi (from kss)
  Downloading tossi-0.3.1.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting distance (from kss)
  Downloading Distance-0.1.3.tar.gz (180 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.3/180.3 kB 12.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyyaml==6.0 (from kss)
  Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting unidecode (from kss)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting cmudict (from kss)
  Downloading cmudict-1.0.32-py3-none-any.whl.metadata (3.6 kB)
Collecting koparadigm (from kss)
  Downloading koparadigm-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Collecting kollocate (from kss)
  Downloading kollocate-0.0.2-py3-none-any.whl.metadata (1.8 kB)
Collecting bs4 (from kss)
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from kss) (2.0.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.11/dist-packages (from kss) (8.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from kss) (1.15.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4->kss) (4.13.4)
Collecting importlib-metadata>=5 (from cmudict->kss)
  Downloading importlib_metadata-8.7.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: importlib-resources>=5 in /usr/local/lib/python3.11/dist-packages (from cmudict->kss) (6.5.2)
Collecting whoosh (from kollocate->kss)
  Downloading Whoosh-2.7.4-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting xlrd==1.2.0 (from koparadigm->kss)
  Downloading xlrd-1.2.0-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.11/dist-packages (from pecab->kss) (20.0.0)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from pecab->kss) (2024.11.6)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.11/dist-packages (from pytest->kss) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from pytest->kss) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest->kss) (1.6.0)
Collecting bidict (from tossi->kss)
  Downloading bidict-0.23.1-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from tossi->kss) (1.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata>=5->cmudict->kss) (3.22.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4->kss) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4->kss) (4.14.0)
Downloading emoji-1.2.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 12.0 MB/s eta 0:00:00
Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 48.5 MB/s eta 0:00:00
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading cmudict-1.0.32-py3-none-any.whl (939 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 939.4/939.4 kB 45.4 MB/s eta 0:00:00
Downloading hangul_jamo-1.0.1-py3-none-any.whl (4.4 kB)
Downloading jamo-0.4.1-py3-none-any.whl (9.5 kB)
Downloading kollocate-0.0.2-py3-none-any.whl (72.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 MB 16.0 MB/s eta 0:00:00
Downloading koparadigm-0.10.0-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 59.7 MB/s eta 0:00:00
Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB 8.8 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 18.5 MB/s eta 0:00:00
Downloading importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
Downloading bidict-0.23.1-py3-none-any.whl (32 kB)
Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.8/468.8 kB 28.2 MB/s eta 0:00:00
Building wheels for collected packages: kss, distance, pecab, tossi
  Building wheel for kss (pyproject.toml) ... done
  Created wheel for kss: filename=kss-6.0.4-py3-none-any.whl size=1089430 sha256=8a8a9bc2060a7fb384304ba391643603e24de65c176f826e558bde7801f4f63a
  Stored in directory: /root/.cache/pip/wheels/86/c9/5f/69b8fe9751eefbb5d087932ddf58d0f121b8e545335af7fe4e
  Building wheel for distance (pyproject.toml) ... done
  Created wheel for distance: filename=distance-0.1.3-py3-none-any.whl size=16321 sha256=bb5abce9214c56c9a71837d21259e4f03d68b879c37989d5d3f03508a370db5a
  Stored in directory: /root/.cache/pip/wheels/fb/cd/9c/3ab5d666e3bcacc58900b10959edd3816cc9557c7337986322
  Building wheel for pecab (pyproject.toml) ... done
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646750 sha256=a036f615e3c5e5caa1c6f65a6eea8cad7615bdfaac76b18f2f86d03b8a186890
  Stored in directory: /root/.cache/pip/wheels/c9/0d/97/ca2bb361e44a80f4c63efe6f6438ff903fd1ab5640eedabc1b
  Building wheel for tossi (pyproject.toml) ... done
  Created wheel for tossi: filename=tossi-0.3.1-py3-none-any.whl size=12181 sha256=a25afc1f47c32fca844ec96836cd0727682711107132ba6494cc9600e9cc8d6c
  Stored in directory: /root/.cache/pip/wheels/36/1a/7e/0b78039c20678a6682f03cca4295efaa5fb55a3d10d7e9837a
Successfully built kss distance pecab tossi
Installing collected packages: whoosh, jamo, hangul-jamo, emoji, distance, xlrd, unidecode, pyyaml, kollocate, importlib-metadata, bidict, tossi, pecab, koparadigm, cmudict, bs4, kss
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.2
    Uninstalling PyYAML-6.0.2:
      Successfully uninstalled PyYAML-6.0.2
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.6.4
    Uninstalling importlib-metadata-4.6.4:
      Successfully uninstalled importlib-metadata-4.6.4
Successfully installed bidict-0.23.1 bs4-0.0.2 cmudict-1.0.32 distance-0.1.3 emoji-1.2.0 hangul-jamo-1.0.1 importlib-metadata-8.7.0 jamo-0.4.1 kollocate-0.0.2 koparadigm-0.10.0 kss-6.0.4 pecab-1.0.8 pyyaml-6.0 tossi-0.3.1 unidecode-1.4.0 whoosh-2.7.4 xlrd-1.2.0

^C
^C

In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import random

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DataSet/네이버포털_전처리완료.csv", encoding = "utf-8-sig")

In [ ]:
df.head()

                                              review        data
0  꽃가루 알러지 없는 부모님은 모르는 아이의 꽃가루 알러지 시작되었습니다 이 글을 봄...  2022-04-10
1  꽃가루 알러지 있는 자녀 두신 부모님 보세요 네이버 꽃가루 지수 검색하면 꽃가루 소...  2021-05-09
2  부산 유아 아토피 한의학에서 바라보는 원인과 증상에 대하여 가려움에 밤잠 못 이루는...  2025-04-14
3  꽃가루 알러지 있으신 자녀 키우시는 분들 보세요 학기초만 되면 보통 중간고사 기간부...  2021-04-18
4  어린이 운동회에 참여하다 이제 겨울이 가고 봄이 찾아왔다 봄이란 무엇인가 봄은 본디...  2024-04-19

**섞어서 임의로 5만건 추출**

In [ ]:
shuffled_df = df.sample(frac=1).reset_index(drop=True)

## LLM - 5만건 테스트/훈련셋 분리해서 만들기
각단계 참조

##공통수행 전처리 1단계

### kss 문장 **분리**

In [ ]:
import pandas as pd
from kss import split_sentences
from tqdm import tqdm

tqdm.pandas()
# 텍스트가 담긴 컬럼명 (실제 이름에 맞게 수정)
text_column = "review"
# 문장 분리
shuffled_df["sentences"] = shuffled_df[text_column].progress_apply(lambda x: split_sentences(x, backend='mecab'))

ModuleNotFoundError: No module named 'kss'

In [ ]:
shuffled_df.to_csv("/content/drive/MyDrive/DataSet/shuffled_df_sentences.csv", encoding = "utf-8-sig")

### 1차 Rule 기반 광고, 소설, 홍보글 제거
: 라벨링 단계

In [ ]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("/content/drive/MyDrive/DataSet/shuffled_df_sentences.csv", encoding="cp949")

# --- 키워드 사전 정의 ---
person_keywords = [
    "나는", "제가", "저는", "우리", "남편", "아내", "아이", "딸", "아들",
    "힘들", "고민", "좋아하", "싫어하", "사랑", "짜증", "속상", "행복", "걱정", "눈물"
]

fiction_keywords = [
    "그는", "그녀는", "되뇌었다", "속삭였다", "눈물이", "바라보며", "기억했다",
    "미소를 지었다", "한참을", "창밖을", "어둠", "사라졌다", "느껴졌다"
]

religious_keywords = [
    "하나님", "예수", "성령", "회개", "지옥", "천국", "복음", "기도", "전도", "영혼", "창조",
    "죄", "구원", "용서", "믿음", "십자가", "사탄", "말씀", "믿으십시오", "사람은 죄인입니다",
    "말세", "말세지말", "마귀", "다시 태어나", "지음받아야", "영적", "부활", "기독교"
]

ad_keywords = [
    "상품", "옵션", "ml", "세트", "강화유리", "액정보호필름", "보호필름", "갤럭시탭", "최저가격", "적립", "배송"
]

system_messages = [
    "문제가 발생했습니다", "다시 시도해주세요", "페이지를 찾을 수 없습니다", "시스템 오류", "불편을 드려 죄송합니다"
]

url_keywords = [
    "http", "https", "naver", "com", "smartstore", "storefarm", "kindlycare", "blog", "카인들리케어",
    "네이버쇼핑", "스마트스토어", "브랜드", "공식몰", "kr", "소소한 일상에 행복을", "인스타그램"
]

ad_descriptive_keywords = [
    "장점", "단점", "기능", "특징", "효과적", "효율적", "성능", "방수", "방풍", "편안함",
    "내구성", "디자인", "착용감", "활동성", "추천", "최적", "우수", "차단", "제공",
    "즐길 수 있습니다", "완벽한", "보장", "우수한", "탁월한"
]

msg_request_keywords = [
    "쪽지", "쪽찌", "보냈", "보낼께", "부탁드려", "성함", "업체", "정보", "알려주", "알수있"
]

encyclopedic_keywords = [
    "설명", "의미", "정의", "특징", "성분", "화학식", "연구", "사용", "효능", "발견", "구성",
    "기원", "기술", "재료", "원리", "효과", "원소", "명칭", "개념", "유래", "발생"
]

# --- 1차 라벨링 ---
def is_ad_sentence(sentence: str) -> bool:
    return any(kw in sentence for kw in ad_keywords)

def is_person_sentence(sentence: str) -> bool:
    return any(kw in sentence for kw in person_keywords)

def initial_label(sentence: str) -> int:
    if is_ad_sentence(sentence):
        return 0
    elif is_person_sentence(sentence):
        return 1
    else:
        return 1  # 기본값

df['label'] = df['sentence'].astype(str).apply(initial_label)

# --- 문서 단위 재분류 ---
grouped = df[df['label'] == 1].groupby("doc_id")

fiction_doc_ids = {
    doc_id for doc_id, group in grouped
    if sum(any(kw in str(s) for kw in fiction_keywords) for s in group['sentence']) >= 4
}

religious_doc_ids = {
    doc_id for doc_id, group in grouped
    if sum(any(kw in str(s) for kw in religious_keywords) for s in group['sentence']) >= 5
}

# --- 문장 단위 세부 재분류 ---
def is_encyclopedia(text):
    text = str(text)
    return sum(kw in text for kw in encyclopedic_keywords) >= 10

def relabel(row):
    label = row['label']
    text = str(row['sentence']).lower()
    doc_id = row['doc_id']

    if label != 1:
        return label
    if doc_id in fiction_doc_ids:
        return 2
    if doc_id in religious_doc_ids:
        return 4
    if any(msg in text for msg in system_messages):
        return 5
    if any(kw in text for kw in url_keywords):
        return 6
    if sum(kw in text for kw in ad_descriptive_keywords) >= 2:
        return 7
    if is_encyclopedia(text):
        return 9
    return 1

df['label'] = df.apply(relabel, axis=1)

# --- 쪽지/연락 유도 문장 → 8 ---
def is_label_8_candidate(text):
    text = str(text)
    if "쪽" in text or "성함" in text or "업체" in text or "정보" in text:
        count = sum(kw in text for kw in msg_request_keywords)
        return count >= 2
    return False

df['label'] = df.apply(
    lambda row: 8 if row['label'] == 1 and is_label_8_candidate(row['sentence']) else row['label'],
    axis=1
)

# 저장
df.to_csv("labeled_final_output.csv", index=False, encoding="cp949")

2차적 정제 rule 기반 데이터 정제

In [ ]:
import pandas as pd
import re

# --- 데이터 불러오기 ---
df = pd.read_csv("/content/drive/MyDrive/DataSet/shuffled_df_flat.csv")

# --- 키워드 사전 정의 ---
person_keywords = [
    "나는", "제가", "저는", "우리", "남편", "아내", "아이", "딸", "아들",
    "힘들", "고민", "좋아하", "싫어하", "사랑", "짜증", "속상", "행복", "걱정", "눈물"
]

fiction_keywords = [
    "그는", "그녀는", "되뇌었다", "속삭였다", "눈물이", "바라보며", "기억했다",
    "미소를 지었다", "한참을", "창밖을", "어둠", "사라졌다", "느껴졌다"
]

religious_keywords = [
    "하나님", "예수", "성령", "회개", "지옥", "천국", "복음", "기도", "전도", "영혼", "창조",
    "죄", "구원", "용서", "믿음", "십자가", "사탄", "말씀", "믿으십시오", "사람은 죄인입니다",
    "말세", "말세지말", "마귀", "다시 태어나", "지음받아야", "영적", "부활", "기독교"
]

ad_keywords = [
    "상품", "옵션", "ml", "세트", "강화유리", "액정보호필름", "보호필름", "갤럭시탭", "최저가격", "적립", "배송"
]

system_messages = [
    "문제가 발생했습니다", "다시 시도해주세요", "페이지를 찾을 수 없습니다", "시스템 오류", "불편을 드려 죄송합니다"
]

url_keywords = [
    "http", "https", "naver", "com", "smartstore", "storefarm", "kindlycare", "blog", "카인들리케어",
    "네이버쇼핑", "스마트스토어", "브랜드", "공식몰", "kr", "소소한 일상에 행복을", "인스타그램"
]

ad_descriptive_keywords = [
    "장점", "단점", "기능", "특징", "효과적", "효율적", "성능", "방수", "방풍", "편안함",
    "내구성", "디자인", "착용감", "활동성", "추천", "최적", "우수", "차단", "제공",
    "즐길 수 있습니다", "완벽한", "보장", "우수한", "탁월한"
]

msg_request_keywords = [
    "쪽지", "쪽찌", "보냈", "보낼께", "부탁드려", "성함", "업체", "정보", "알려주", "알수있"
]

encyclopedic_keywords = [
    "설명", "의미", "정의", "특징", "성분", "화학식", "연구", "사용", "효능", "발견", "구성",
    "기원", "기술", "재료", "원리", "효과", "원소", "명칭", "개념", "유래", "발생"
]

# --- 의미 없음 판단 ---
def is_meaningless(text):
    if pd.isna(text):
        return True
    text = str(text).strip().lower()
    meaningless_phrases = [
        "네", "예", "응", "음", "오", "헐", "헉", "ㅋㅋ", "ㅠㅠ", "ㅎㅎ", "굿", "넵",
        "감사", "좋아요", "좋아", "감사합니다", "고마워요", "맞아요", "마자요", "저도요",
        "공감", "수산뇨", "추천해요", "작아요", "무서워요", "힘내세요", "어찌까요", "미투요",
        "왜 안돼", "그러게요", "밧이요", "보내드라", "수이매냐", "매냐", "그립다", "했죠", "안그래요",
        "내용없음", "없음", "내용 없습니다", "해당 없음", "n/a", "none", "-", " "
    ]
    if len(text) <= 5:
        return True
    if any(text == phrase for phrase in meaningless_phrases):
        return True
    if re.fullmatch(r"[.!\?~ㄷㅎㅋㅜㅠ\s]+", text):
        return True
    return False

# --- 1차 라벨링 ---
def is_ad_sentence(sentence: str) -> bool:
    return any(kw in sentence for kw in ad_keywords)

def is_person_sentence(sentence: str) -> bool:
    return any(kw in sentence for kw in person_keywords)

def initial_label(sentence: str) -> int:
    if is_meaningless(sentence):
        return -1
    if is_ad_sentence(sentence):
        return 0
    elif is_person_sentence(sentence):
        return 1
    else:
        return 1

df['label'] = df['sentence'].astype(str).apply(initial_label)

# --- 문서 단위 재분류 (개선된 소설 및 종교 판단 포함) ---
grouped = df[df['label'] == 1].groupby("doc_id")

# ✅ 개선된 소설 판별 로직
def is_fiction_doc(group):
    count = sum(
        sum(kw in str(s) for kw in fiction_keywords) >= 2
        for s in group['sentence']
    )
    return count >= 5


fiction_doc_ids = {
    doc_id for doc_id, group in grouped
    if is_fiction_doc(group)
}

# ✅ 종교 문서 판단 로직
def is_religious_doc(group):
    count = sum(
        1 for s in group['sentence']
        if sum(kw in str(s) for kw in religious_keywords) >= 2
    )
    return count >= 5

religious_doc_ids = {
    doc_id for doc_id, group in grouped
    if is_religious_doc(group)
}

# --- 문장 단위 재분류 ---
def is_encyclopedia(text):
    text = str(text)
    return sum(kw in text for kw in encyclopedic_keywords) >= 10

def relabel(row):
    label = row['label']
    text = str(row['sentence']).lower()
    doc_id = row['doc_id']

    if label != 1:
        return label
    if doc_id in fiction_doc_ids:
        return 2
    if doc_id in religious_doc_ids:
        return 4
    if any(msg in text for msg in system_messages):
        return 5
    if any(kw in text for kw in url_keywords):
        return 6
    if sum(kw in text for kw in ad_descriptive_keywords) >= 5:
        return 7
    if is_encyclopedia(text):
        return 9
    return 1

df['label'] = df.apply(relabel, axis=1)

# --- 쪽지 유도 → 8 ---
def is_label_8_candidate(text):
    text = str(text)
    if "쪽" in text or "성함" in text or "업체" in text or "정보" in text:
        count = sum(kw in text for kw in msg_request_keywords)
        return count >= 2
    return False

df['label'] = df.apply(
    lambda row: 8 if row['label'] == 1 and is_label_8_candidate(row['sentence']) else row['label'],
    axis=1
)

# --- 결과 저장 ---
df.to_csv("labeled_final_output.csv", index=False, encoding="cp949")

In [ ]:
import pandas as pd
import re

def apply_custom_labeling(df: pd.DataFrame) -> pd.DataFrame:
    # --- 키워드 사전 정의 ---
    person_keywords = [
        "나는", "제가", "저는", "우리", "남편", "아내", "아이", "딸", "아들",
        "힘들", "고민", "좋아하", "싫어하", "사랑", "짜증", "속상", "행복", "걱정", "눈물"
    ]
    fiction_keywords = [
        "그는", "그녀는", "되뇌었다", "속삭였다", "눈물이", "바라보며", "기억했다",
        "미소를 지었다", "한참을", "창밖을", "어둠", "사라졌다", "느껴졌다"
    ]
    religious_keywords = [
        "하나님", "예수", "성령", "회개", "지옥", "천국", "복음", "기도", "전도", "영혼", "창조",
        "죄", "구원", "용서", "믿음", "십자가", "사탄", "말씀", "믿으십시오", "사람은 죄인입니다",
        "말세", "말세지말", "마귀", "다시 태어나", "지음받아야", "영적", "부활", "기독교"
    ]
    ad_keywords = ["상품", "옵션", "ml", "세트", "강화유리", "액정보호필름", "보호필름", "갤럭시탭", "최저가격", "적립", "배송"]
    system_messages = ["문제가 발생했습니다", "다시 시도해주세요", "페이지를 찾을 수 없습니다", "시스템 오류", "불편을 드려 죄송합니다"]
    url_keywords = ["http", "https", "naver", "com", "smartstore", "storefarm", "kindlycare", "blog", "카인들리케어",
                    "네이버쇼핑", "스마트스토어", "브랜드", "공식몰", "kr", "소소한 일상에 행복을", "인스타그램"]
    ad_descriptive_keywords = [
        "장점", "단점", "기능", "특징", "효과적", "효율적", "성능", "방수", "방풍", "편안함",
        "내구성", "디자인", "착용감", "활동성", "추천", "최적", "우수", "차단", "제공",
        "즐길 수 있습니다", "완벽한", "보장", "우수한", "탁월한"
    ]
    msg_request_keywords = ["쪽지", "쪽찌", "보냈", "보낼께", "부탁드려", "성함", "업체", "정보", "알려주", "알수있"]
    encyclopedic_keywords = [
        "설명", "의미", "정의", "특징", "성분", "화학식", "연구", "사용", "효능", "발견", "구성",
        "기원", "기술", "재료", "원리", "효과", "원소", "명칭", "개념", "유래", "발생"
    ]
    meaningless_phrases = [
        "네", "예", "응", "음", "오", "헐", "헉", "ㅋㅋ", "ㅠㅠ", "ㅎㅎ", "굿", "넵",
        "감사", "좋아요", "좋아", "감사합니다", "고마워요", "맞아요", "마자요", "저도요",
        "공감", "수산뇨", "추천해요", "작아요", "무서워요", "힘내세요", "어찌까요", "미투요",
        "왜 안돼", "그러게요", "밧이요", "보내드라", "수이매냐", "매냐", "그립다", "했죠", "안그래요",
        "내용없음", "없음", "내용 없습니다", "해당 없음", "n/a", "none", "-", " "
    ]

    # --- 라벨링 보조 함수 ---
    def is_meaningless(text):
        if pd.isna(text):
            return True
        text = str(text).strip().lower()
        if len(text) <= 5:
            return True
        if any(text == phrase for phrase in meaningless_phrases):
            return True
        if re.fullmatch(r"[.!\?~ㄷㅎㅋㅜㅠ\s]+", text):
            return True
        return False

    def initial_label(sentence: str) -> int:
        if is_meaningless(sentence):
            return -1
        if any(kw in sentence for kw in ad_keywords):
            return 0
        elif any(kw in sentence for kw in person_keywords):
            return 1
        else:
            return 1

    df['label'] = df['sentence'].astype(str).apply(initial_label)

    # --- 문서 단위 그룹 재분류 ---
    grouped = df[df['label'] == 1].groupby("doc_id")

    def is_fiction_doc(group):
        count = sum(
            sum(kw in str(s) for kw in fiction_keywords) >= 2
            for s in group['sentence']
        )
        return count >= 5

    def is_religious_doc(group):
        count = sum(
            1 for s in group['sentence']
            if sum(kw in str(s) for kw in religious_keywords) >= 2
        )
        return count >= 5

    fiction_doc_ids = {doc_id for doc_id, group in grouped if is_fiction_doc(group)}
    religious_doc_ids = {doc_id for doc_id, group in grouped if is_religious_doc(group)}

    def is_encyclopedia(text):
        return sum(kw in str(text) for kw in encyclopedic_keywords) >= 6

    def relabel(row):
        label, text, doc_id = row['label'], str(row['sentence']).lower(), row['doc_id']
        if label != 1:
            return label
        if doc_id in fiction_doc_ids:
            return 2
        if doc_id in religious_doc_ids:
            return 4
        if any(msg in text for msg in system_messages):
            return 5
        if any(kw in text for kw in url_keywords):
            return 6
        if sum(kw in text for kw in ad_descriptive_keywords) >= 5:
            return 7
        if is_encyclopedia(text):
            return 9
        return 1

    df['label'] = df.apply(relabel, axis=1)

    def is_label_8_candidate(text):
        text = str(text)
        if "쪽" in text or "성함" in text or "업체" in text or "정보" in text:
            return sum(kw in text for kw in msg_request_keywords) >= 2
        return False

    df['label'] = df.apply(
        lambda row: 8 if row['label'] == 1 and is_label_8_candidate(row['sentence']) else row['label'],
        axis=1
    )
    mask = (
    df["sentence"].str.fullmatch(r'[A-Za-z ]+', na=False) &  # 영어 문장만
    (df["label"] == 1)                                       # label이 1인 경우만
    )

    df.loc[mask, "label"] = 10

    return df

## 문장 전처리 구성
1. shuffled_df_sentences : 전체 데이터 중에서 5만건 랜덤 선정
2. shuffled_df_sentences : 데이터를 훈련셋 fit에 맞춰서 분리

In [ ]:
shuffled_df = pd.read_csv("/content/drive/MyDrive/DataSet/shuffled_df_sentences.csv", encoding = "utf-8-sig")

In [ ]:
import re

def fast_token_parser(s):
    return re.findall(r"'(.*?)'", s)

In [ ]:
import pandas as pd
import numpy as np

문장 리스트화 하고 문장단위로 분리

In [ ]:
rows = []

for doc_idx, row in shuffled_df.iterrows():
    sentences = row["sentences_clean"]
    for idx, sentence in enumerate(sentences):
        rows.append({
            "sentence": sentence,
            "doc_id": doc_idx,
            "sentence_idx": idx
        })

flat_df = pd.DataFrame(rows)

In [ ]:
print(flat_df.head())
print(len(flat_df))

                                            sentence  doc_id  sentence_idx
0  The Summer Days 단편 소개팅해서 개월 좀 넘게 만났고 헤어진지는 주 정...       0             0
1  둘다 살 동갑이고 제가 좋아하는것보다 본인이 절 덜 좋아하는거 같다길래 의지가 있는...       0             1
2        그리고 더는 자신이 없다는 얘기를 듣고 결국 잘지내자는 말을 끝으로 끝났습니다       0             2
3  우선 전남친이 불만이었고 화냈던 포인트를 말하자면 뭔가 본인이 원하는 이상형이 뚜렷...       0             3
4  머리 스타일이라던지 옷입는 취향이라던지 제가 추위를 좀 많이 타는 편이라 겨울에 코...       0             4
3799808

In [ ]:
#flat_df 저장하기
flat_df.to_csv("/content/drive/MyDrive/DataSet/shuffled_df_flat.csv")

kss 문장 분리 실행기가 너무 느려서 실행한것

In [ ]:
#라벨링을 위해서 분할해서 저장하기

# 1. 원본 CSV 파일 경로
file_path = '/content/drive/MyDrive/DataSet/shuffled_df_flat.csv'

# 파일 이름을 필요에 따라 수정하세요

# 2. CSV 파일 불러오기 (인코딩 자동 선택)
encodings = ['utf-8', 'cp949', 'ISO-8859-1']
for enc in encodings:
    try:
        df = pd.read_csv(file_path, encoding=enc)
        break
    except Exception as e:
        continue

# 3. 총 행 수 기준으로 5개로 균등 분할
chunk_size = len(df) // 5
chunks = [df.iloc[i * chunk_size: (i + 1) * chunk_size] for i in range(4)]
chunks.append(df.iloc[4 * chunk_size:])  # 마지막 chunk는 남은 모든 행 포함

# 4. 각각 저장
for i, chunk in enumerate(chunks):
    output_path = f'/content/drive/MyDrive/DataSet/shuffled_part_{i+1}.csv'
    chunk.to_csv(output_path, index=False, encoding='utf-8')
    print(f'Saved: {output_path}')

Saved: /content/drive/MyDrive/DataSet/shuffled_part_1.csv
Saved: /content/drive/MyDrive/DataSet/shuffled_part_2.csv
Saved: /content/drive/MyDrive/DataSet/shuffled_part_3.csv
Saved: /content/drive/MyDrive/DataSet/shuffled_part_4.csv
Saved: /content/drive/MyDrive/DataSet/shuffled_part_5.csv

위에 라벨링을 위한  rule 기반 파싱 함수 적용

In [ ]:
labeled_df = apply_custom_labeling(flat_df)

In [ ]:
labeled_df.to_csv("/content/drive/MyDrive/DataSet/suffled_sample/labeled_final_output.csv", index=False, encoding="cp949")

### 무의미한 rule 기반 제거가능한 문자 제거

In [ ]:
labels_to_remove = [-1, 10, 6, 8, 5]

# 해당 라벨이 아닌 행만 남기기
filtered_df = labeled_df[~labeled_df['label'].isin(labels_to_remove)]

# 결과 확인 (선택)
print(filtered_df['label'].value_counts())

# 필요 시 저장
filtered_df.to_csv("/content/drive/MyDrive/DataSet/suffled_sample/filtered_output.csv", index=False, encoding="utf-8-sig")

label
1    2838724
0     421352
4     317385
2      79313
7        174
9         63
Name: count, dtype: int64

In [ ]:
def map_to_merged_label(label):
    if label in [0, 7]:
        return 0  # 광고성
    elif label == 1:
        return 1  # 사용자 감성 표현
    elif label == 2:
        return 2  # 픽션(문학적 문체)
    elif label == 4:
        return 3  # 종교적 정보
    elif label == 9:
        return 4  # 백과사전 식 정보글
    else:
        return -1  # 예외 처리용 (필요 시 필터링 가능)

# 새로운 컬럼으로 저장
train_df['label'] = train_df['label'].apply(map_to_merged_label)

cross vaildation 검증시 안해도 됨

In [ ]:
from sklearn.model_selection import train_test_split
# 문서 단위로 나누기
doc_ids = filtered_df["doc_id"].unique()
train_ids, test_ids = train_test_split(doc_ids, test_size=0.2, random_state=42)

train_df = filtered_df[filtered_df["doc_id"].isin(train_ids)]
test_df = filtered_df[filtered_df["doc_id"].isin(test_ids)]

In [ ]:
train_df.to_csv("/content/drive/MyDrive/DataSet/suffled_sample/train.csv", index=False)
test_df.to_csv("/content/drive/MyDrive/DataSet/suffled_sample/test.csv", index=False)

NameError: name 'train_df' is not defined

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train_df= pd.read_csv("/content/drive/MyDrive/DataSet/suffled_sample/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/DataSet/suffled_sample/test.csv")

In [ ]:
test_df["merged_label"].value_counts()

merged_label
1    580718
0     84223
3     65241
2     17614
4        15
Name: count, dtype: int64

##임베딩 - kobert
소주점 tolist 변환과정에서 미세한 소수점 차이 존재

train/test

In [ ]:
train_df= pd.read_csv("/content/drive/MyDrive/DataSet/suffled_sample/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/DataSet/suffled_sample/test.csv")

In [ ]:
from imblearn.over_sampling import SMOTE, RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
import random
import os

# 디바이스 설정
import torch

seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = "cuda" if torch.cuda.is_available() else "cpu"


model = SentenceTransformer('jhgan/ko-sroberta-multitask', device=device)

# 임베딩 대상 문장 리스트
embedding = train_df["sentence"].tolist()
y = train_df['merged_label'].values

# 중간 저장 폴더
save_dir = "/content/drive/MyDrive/DataSet/suffled_sample"
os.makedirs(save_dir, exist_ok=True)

# 임베딩 및 중간 저장
batch_size=5000
X_all = []
model.eval()
for i in range(0, len(embedding), batch_size):
    batch_sentences = embedding[i:i+batch_size]
    X_batch = model.encode(batch_sentences, batch_size=5000, convert_to_numpy=True, normalize_embeddings=False, show_progress_bar=True)
    X_all.extend(X_batch)

    # 중간 저장: numpy 형식으로 저장
    np.save(os.path.join(save_dir, f"train_batch1000_{i//batch_size:04d}.npy"), X_batch)
    print(f"[{i}/{len(embedding)}] 저장됨")

# 모든 임베딩 합치기
X = np.vstack(X_all)

# 필요하다면 같이 저장
np.save(os.path.join(save_dir, "train_X_final.npy"), X)
pd.Series(y).to_csv(os.path.join(save_dir, "train_y_labels.csv"), index=False)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[0/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[5000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[10000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[15000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[20000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[25000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[30000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[35000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[40000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[45000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[50000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[55000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[60000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[65000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[70000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[75000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[80000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[85000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[90000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[95000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[100000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[105000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[110000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[115000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[120000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[125000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[130000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[135000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[140000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[145000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[150000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[155000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[160000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[165000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[170000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[175000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[180000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[185000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[190000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[195000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[200000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[205000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[210000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[215000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[220000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[225000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[230000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[235000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[240000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[245000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[250000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[255000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[260000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[265000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[270000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[275000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[280000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[285000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[290000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[295000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[300000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[305000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[310000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[315000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[320000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[325000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[330000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[335000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[340000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[345000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[350000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[355000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[360000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[365000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[370000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[375000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[380000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[385000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[390000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[395000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[400000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[405000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[410000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[415000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[420000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[425000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[430000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[435000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[440000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[445000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[450000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[455000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[460000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[465000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[470000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[475000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[480000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[485000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[490000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[495000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[500000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[505000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[510000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[515000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[520000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[525000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[530000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[535000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[540000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[545000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[550000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[555000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[560000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[565000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[570000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[575000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[580000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[585000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[590000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[595000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[600000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[605000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[610000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[615000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[620000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[625000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[630000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[635000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[640000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[645000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[650000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[655000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[660000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[665000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[670000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[675000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[680000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[685000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[690000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[695000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[700000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[705000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[710000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[715000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[720000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[725000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[730000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[735000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[740000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[745000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[750000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[755000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[760000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[765000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[770000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[775000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[780000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[785000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[790000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[795000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[800000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[805000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[810000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[815000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[820000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[825000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[830000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[835000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[840000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[845000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[850000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[855000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[860000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[865000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[870000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[875000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[880000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[885000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[890000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[895000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[900000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[905000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[910000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[915000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[920000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[925000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[930000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[935000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[940000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[945000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[950000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[955000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[960000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[965000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[970000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[975000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[980000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[985000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[990000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[995000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1000000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1005000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1010000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1015000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1020000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1025000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1030000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1035000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1040000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1045000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1050000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1055000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1060000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1065000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1070000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1075000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1080000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1085000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1090000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1095000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1100000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1105000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1110000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1115000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1120000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1125000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1130000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1135000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1140000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1145000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1150000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1155000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1160000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1165000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1170000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1175000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1180000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1185000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1190000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1195000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1200000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1205000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1210000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1215000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1220000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1225000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1230000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1235000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1240000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1245000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1250000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1255000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1260000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1265000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1270000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1275000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1280000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1285000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1290000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1295000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1300000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1305000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1310000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1315000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1320000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1325000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1330000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1335000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1340000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1345000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1350000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1355000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1360000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1365000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1370000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1375000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1380000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1385000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1390000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1395000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1400000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1405000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1410000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1415000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1420000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1425000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1430000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1435000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1440000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1445000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1450000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1455000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1460000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1465000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1470000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1475000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1480000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1485000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1490000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1495000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1500000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1505000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1510000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1515000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1520000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1525000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1530000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1535000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1540000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1545000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1550000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1555000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1560000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1565000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1570000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1575000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1580000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1585000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1590000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1595000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1600000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1605000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1610000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1615000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1620000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1625000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1630000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1635000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1640000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1645000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1650000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1655000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1660000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1665000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1670000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1675000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1680000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1685000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1690000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1695000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1700000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1705000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1710000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1715000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1720000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1725000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1730000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1735000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1740000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1745000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1750000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1755000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1760000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1765000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1770000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1775000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1780000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1785000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1790000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1795000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1800000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1805000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1810000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1815000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1820000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1825000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1830000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1835000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1840000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1845000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1850000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1855000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1860000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1865000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1870000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1875000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1880000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1885000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1890000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1895000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1900000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1905000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1910000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1915000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1920000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1925000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1930000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1935000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1940000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1945000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1950000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1955000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1960000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1965000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1970000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1975000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1980000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1985000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1990000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[1995000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2000000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2005000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2010000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2015000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2020000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2025000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2030000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2035000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2040000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2045000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2050000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2055000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2060000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2065000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2070000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2075000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2080000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2085000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2090000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2095000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2100000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2105000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2110000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2115000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2120000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2125000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2130000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2135000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2140000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2145000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2150000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2155000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2160000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2165000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2170000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2175000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2180000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2185000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2190000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2195000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2200000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2205000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2210000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2215000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2220000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2225000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2230000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2235000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2240000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2245000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2250000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2255000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2260000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2265000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2270000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2275000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2280000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2285000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2290000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2295000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2300000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2305000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2310000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2315000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2320000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2325000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2330000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2335000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2340000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2345000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2350000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2355000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2360000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2365000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2370000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2375000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2380000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2385000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2390000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2395000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2400000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2405000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2410000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2415000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2420000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2425000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2430000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2435000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2440000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2445000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2450000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2455000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2460000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2465000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2470000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2475000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2480000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2485000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2490000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2495000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2500000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2505000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2510000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2515000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2520000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2525000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2530000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2535000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2540000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2545000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2550000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2555000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2560000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2565000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2570000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2575000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2580000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2585000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2590000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2595000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2600000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2605000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2610000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2615000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2620000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2625000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2630000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2635000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2640000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2645000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2650000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2655000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2660000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2665000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2670000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2675000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2680000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2685000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2690000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2695000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2700000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2705000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2710000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2715000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2720000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2725000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2730000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2735000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2740000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2745000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2750000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2755000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2760000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2765000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2770000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2775000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2780000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2785000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2790000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2795000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2800000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2805000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2810000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2815000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2820000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2825000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2830000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2835000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2840000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2845000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2850000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2855000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2860000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2865000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2870000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2875000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2880000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2885000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2890000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2895000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2900000/2909200] 저장됨

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[2905000/2909200] 저장됨

In [ ]:
train_df["embedding"] = list(X)

In [ ]:
test_df["merged_label"].value_counts()

merged_label
1    580718
0     84223
3     65241
2     17614
4        15
Name: count, dtype: int64

In [ ]:
Totall_Data = pd.concat([train_df, test_df])

In [ ]:
Totall_Data["merged_label"].value_counts()

merged_label
1    2838724
0     421526
3     317385
2      79313
4         63
Name: count, dtype: int64

In [ ]:
import torch, gc
gc.collect()  # Python 객체 정리
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

###중간에 멈추는 경우

In [ ]:
from imblearn.over_sampling import SMOTE, RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
import os
# 디바이스 설정
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

# 중간 저장 폴더
save_dir = "/content/drive/MyDrive/DataSet/suffled_sample"
os.makedirs(save_dir, exist_ok=True)

# 모델 로드
model = SentenceTransformer('jhgan/ko-sroberta-multitask', device=device)

start_index = 284963  # 시작 인덱스
batch_size = 32

# 부분 리스트 및 레이블 슬라이싱
embedding = train_df["sentence"].tolist()[start_index:]
y = train_df['merged_label'].values[start_index:]

X_all = []
for i in range(0, len(embedding), batch_size):
    batch_sentences = embedding[i:i+batch_size]
    X_batch = model.encode(batch_sentences, show_progress_bar=False)
    X_all.extend(X_batch)

    # 저장: 전체 인덱스를 기준으로 파일명 생성
    global_index = start_index + i
    np.save(os.path.join(save_dir, f"batch_{global_index//batch_size:04d}.npy"), X_batch)
    print(f"[{global_index}/{start_index + len(embedding)}] 저장됨")
    print((global_index//batch_size))
    if (global_index//batch_size) == 8978:
        break

# 임베딩 병합 및 저장
X = np.vstack(X_all)
np.save(os.path.join(save_dir, f"X_final_from_{start_index}.npy"), X)
pd.Series(y).to_csv(os.path.join(save_dir, f"y_labels_from_{start_index}.csv"), index=False)

[284963/2909200] 저장됨
8905
[284995/2909200] 저장됨
8906
[285027/2909200] 저장됨
8907
[285059/2909200] 저장됨
8908
[285091/2909200] 저장됨
8909
[285123/2909200] 저장됨
8910
[285155/2909200] 저장됨
8911
[285187/2909200] 저장됨
8912
[285219/2909200] 저장됨
8913
[285251/2909200] 저장됨
8914
[285283/2909200] 저장됨
8915
[285315/2909200] 저장됨
8916
[285347/2909200] 저장됨
8917
[285379/2909200] 저장됨
8918
[285411/2909200] 저장됨
8919
[285443/2909200] 저장됨
8920
[285475/2909200] 저장됨
8921
[285507/2909200] 저장됨
8922
[285539/2909200] 저장됨
8923
[285571/2909200] 저장됨
8924
[285603/2909200] 저장됨
8925
[285635/2909200] 저장됨
8926
[285667/2909200] 저장됨
8927
[285699/2909200] 저장됨
8928
[285731/2909200] 저장됨
8929
[285763/2909200] 저장됨
8930
[285795/2909200] 저장됨
8931
[285827/2909200] 저장됨
8932
[285859/2909200] 저장됨
8933
[285891/2909200] 저장됨
8934
[285923/2909200] 저장됨
8935
[285955/2909200] 저장됨
8936
[285987/2909200] 저장됨
8937
[286019/2909200] 저장됨
8938
[286051/2909200] 저장됨
8939
[286083/2909200] 저장됨
8940
[286115/2909200] 저장됨
8941
[286147/2909200] 저장됨
8942
[286179/2909200] 저장됨
8943
[286211/2909200] 저장됨
8944
[286243/2909200] 저장됨
8945
[286275/2909200] 저장됨
8946
[286307/2909200] 저장됨
8947
[286339/2909200] 저장됨
8948
[286371/2909200] 저장됨
8949
[286403/2909200] 저장됨
8950
[286435/2909200] 저장됨
8951
[286467/2909200] 저장됨
8952
[286499/2909200] 저장됨
8953
[286531/2909200] 저장됨
8954
[286563/2909200] 저장됨
8955
[286595/2909200] 저장됨
8956
[286627/2909200] 저장됨
8957
[286659/2909200] 저장됨
8958
[286691/2909200] 저장됨
8959
[286723/2909200] 저장됨
8960
[286755/2909200] 저장됨
8961
[286787/2909200] 저장됨
8962
[286819/2909200] 저장됨
8963
[286851/2909200] 저장됨
8964
[286883/2909200] 저장됨
8965
[286915/2909200] 저장됨
8966
[286947/2909200] 저장됨
8967
[286979/2909200] 저장됨
8968
[287011/2909200] 저장됨
8969
[287043/2909200] 저장됨
8970
[287075/2909200] 저장됨
8971
[287107/2909200] 저장됨
8972
[287139/2909200] 저장됨
8973
[287171/2909200] 저장됨
8974
[287203/2909200] 저장됨
8975
[287235/2909200] 저장됨
8976
[287267/2909200] 저장됨
8977
[287299/2909200] 저장됨
8978

병합하기

In [ ]:
import os
import numpy as np

# 저장된 배치 파일 경로
save_dir = "/content/drive/MyDrive/DataSet/suffled_sample"

# 모든 batch 파일 정렬
npy_files = sorted(
    [f for f in os.listdir(save_dir) if f.startswith("batch_") and f.endswith(".npy")],
    key=lambda x: int(x.split("_")[1].split(".")[0])
)

# ✅ 현재 파트 설정 (세션마다 다르게 바꿔야 함!)
part_idx = 5
files_per_part = 10000

# 파트 범위 설정
start = part_idx * files_per_part
end = start + files_per_part
npy_files_part = npy_files[start:end]

# 병합
X_all = []
for fname in npy_files_part:
    batch = np.load(os.path.join(save_dir, fname))
    X_all.append(batch)
    print(f"{fname} 로드됨")

X_merged = np.vstack(X_all)
print(f"[파트 {part_idx}] 병합 shape: {X_merged.shape}")

# 저장
np.save(os.path.join(save_dir, f"X_final_part_{part_idx}.npy"), X_merged)

KeyboardInterrupt:

다시 한번 한개로 만들기

In [ ]:
import os
import numpy as np

# 저장 경로
save_dir = "/content/drive/MyDrive/DataSet/suffled_sample"

# part 파일 이름 생성 (0~8)
part_files = [f"X_final_part_{i}.npy" for i in range(10)]

# 병합
X_parts = []
for fname in part_files:
    path = os.path.join(save_dir, fname)
    print(f"🔄 {fname} 로딩 중...")
    X = np.load(path)
    X_parts.append(X)
    print(f"✅ shape: {X.shape}")

# 전체 병합
X_all = np.vstack(X_parts)
print(f"🎉 전체 병합 shape: {X_all.shape}")

# 최종 저장
np.save(os.path.join(save_dir, "X_final_all.npy"), X_all)
print("💾 X_final_all.npy 저장 완료")

🔄 X_final_part_0.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_1.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_2.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_3.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_4.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_5.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_6.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_7.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_8.npy 로딩 중...
✅ shape: (320000, 768)
🔄 X_final_part_9.npy 로딩 중...
✅ shape: (29200, 768)
🎉 전체 병합 shape: (2909200, 768)
💾 X_final_all.npy 저장 완료

In [ ]:
train = np.load("/content/drive/MyDrive/DataSet/suffled_sample/X_final_all.npy")
test = np.load("/content/drive/MyDrive/DataSet/suffled_sample/test_X_final.npy")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/DataSet/suffled_sample/test_X_final_all.npy'

In [ ]:
train_df["embedding"] = list(train)
test_df["embedding"] = list(test)

In [ ]:
train_df["merged_label"].value_counts()

merged_label
1    2258006
0     337303
3     252144
2      61699
4         48
Name: count, dtype: int64

In [ ]:
train_totall = pd.concat([train_df, test_df])

In [ ]:
len(train_totall)

3657011

In [ ]:
emb1 = model.encode(test_df["sentence"][100], convert_to_numpy=True)
emb2 = model.encode(test_df["sentence"][100], convert_to_numpy=True)

np.allclose(emb1, emb2, atol=1e-6)  # True여야 정상

True

In [ ]:
matching_idx = test_df.index[
   test_df["embedding"].apply(lambda x: np.array_equal(x, X_batch))
].tolist()

print(matching_idx)  # 예: [1]

[]

In [ ]:
model = SentenceTransformer('jhgan/ko-sroberta-multitask', device=device)

In [ ]:
test_df["sentence"][100]

'상품 후기보기유통기한 사용기한 표시의무 대상 상품은 사용기한 이후인 상품 제조국 한국옵션 아토팜 수딩 젤 로션 ml 개 PSP 모두의 골프 포터블 최저가격 원최대 원 적립총 분이상이 개를 주셨습니다'

In [ ]:
X_batch = model.encode(test_df["sentence"][100], show_progress_bar=False)

In [ ]:
X_batch

array([ 1.41409725e-01,  2.31301904e-01,  2.12527230e-01,  8.63969997e-02,
        3.74197006e-01, -5.60273111e-01,  9.50763971e-02, -3.84796737e-03,
        8.66491914e-01, -2.20726252e-01,  4.14837182e-01, -2.25773573e-01,
       -3.97686690e-01,  1.77608296e-01,  2.69867450e-01,  2.46545877e-02,
        3.66385132e-02,  1.67650685e-01, -3.25799286e-01, -3.78762692e-01,
       -8.07964385e-01, -5.35096586e-01,  8.41159374e-02, -2.33489215e-01,
       -3.28113139e-01, -1.26334190e-01, -2.95861334e-01,  4.66363765e-02,
        1.06387055e+00,  5.08943051e-02,  4.03666645e-01,  4.86346073e-02,
       -1.07323825e+00, -2.88435578e-01,  3.15351009e-01, -2.64225513e-01,
       -5.42768061e-01, -5.93493879e-01,  2.11698562e-01,  4.12660569e-01,
       -1.83748845e-02, -3.60820889e-01, -5.69656268e-02,  3.75402540e-01,
        5.94702065e-01, -3.18870991e-01,  1.19594216e-01, -3.36227119e-02,
        1.72981143e-01, -3.82890046e-01, -4.26839292e-01, -2.82811880e-01,
       -2.98971325e-01, -1.81918740e-01,  2.86313325e-01, -1.25191972e-01,
        1.07739545e-01, -4.50572848e-01, -2.85652429e-01, -9.65645850e-01,
        6.48015261e-01, -2.29204640e-01, -9.32845712e-01,  3.06115836e-01,
       -3.62968504e-01,  6.32185340e-02,  7.30472505e-01,  6.10648632e-01,
       -1.86283186e-01, -3.02097201e-01,  4.04350273e-02, -2.78968841e-01,
        3.44343901e-01,  2.27324456e-01,  8.32631886e-02, -1.45912141e-01,
       -1.22793213e-01, -1.02564596e-01,  7.45152473e-01, -2.96806633e-01,
       -5.05945385e-02, -2.73200810e-01, -3.79399657e-01, -2.26511538e-01,
        2.53927499e-01, -4.87804800e-01,  1.21710472e-01, -4.91348684e-01,
        3.14574122e-01, -2.23050252e-01, -3.80615860e-01, -4.99686688e-01,
       -4.84823048e-01,  5.07456422e-01, -2.00257748e-01, -1.28849462e-01,
       -5.37353754e-01, -2.89962530e-01,  7.65442371e-01,  4.39858586e-01,
       -4.10128713e-01,  1.21557403e+00, -6.56958818e-01,  3.41207713e-01,
        3.66513454e-03,  5.03872573e-01,  4.80821393e-02,  7.14638531e-01,
        3.29332143e-01,  1.49203856e-02, -6.51241839e-01, -5.67408383e-01,
        4.73632030e-02,  4.73530084e-01,  9.22278315e-02,  4.08430755e-01,
       -8.93504798e-01,  2.62174785e-01,  6.75999373e-02,  1.27356619e-01,
        6.18196845e-01, -3.67806137e-01, -2.85041216e-03,  3.61017883e-01,
        1.29468724e-01,  1.45579696e-01,  7.65712023e-01,  1.92649057e-03,
        7.20288634e-01, -5.93431331e-02,  1.86639085e-01,  3.58123422e-01,
       -1.93794206e-01,  2.13071480e-01, -2.91149199e-01,  7.39528686e-02,
        4.06815335e-02, -2.61754185e-01,  3.08262169e-01, -2.20224664e-01,
       -8.37172449e-01, -1.01092599e-01,  3.71360749e-01, -4.83983070e-01,
        1.56582728e-01, -9.09872949e-02,  5.59069455e-01, -6.89408123e-01,
       -1.81750074e-01, -5.32421291e-01, -1.12612695e-01, -1.88949704e-01,
       -4.66049433e-01, -3.01391870e-01, -3.29748750e-01,  4.97051150e-01,
        3.30697179e-01,  1.98007986e-01,  1.02755517e-01, -4.07263398e-01,
        3.22545588e-01, -5.34248114e-01, -2.19680175e-01, -1.29473269e-01,
        8.70220084e-03,  3.58494520e-01, -3.25864017e-01,  1.69197649e-01,
       -1.12585694e-01, -1.58713430e-01, -9.95747298e-02, -3.53944629e-01,
       -2.02685162e-01, -3.85009766e-01, -5.56810237e-02,  6.47288561e-01,
       -6.24539375e-01,  4.78470325e-01, -5.37458122e-01,  2.06981763e-01,
        4.84194487e-01, -2.30371505e-02,  3.00227497e-02,  1.54561654e-01,
        1.63768321e-01,  2.83441395e-01,  3.14137042e-01, -2.47259825e-01,
       -4.29706216e-01, -1.76269129e-01,  4.34957705e-02,  1.97413517e-03,
        1.88485801e-01,  2.53322750e-01, -1.35909468e-02,  4.06353384e-01,
        7.47375727e-01, -4.68381904e-02,  1.31701574e-01,  1.54926300e-01,
        6.87643960e-02,  4.98521209e-01,  4.19670454e-04,  7.53578544e-02,
        2.96312273e-01, -6.26016438e-01,  1.52084112e-01,  2.58036286e-01,
       -2.52120167e-01,  1.94517858e-02, -6.58674315e-02,  8.82657230e-01,
       -9.11372676e-02,  4.50059474e-01, -1.18187360e-01, -5.00029661e-02,
        1.15030192e-01,  2.72191733e-01,  6.20729029e-01, -1.41555801e-01,
        8.77571881e-01,  3.78941566e-01,  5.34942091e-01,  6.68495595e-01,
        2.81277955e-01,  1.55354604e-01,  4.55421321e-02,  2.87344068e-01,
        2.69467264e-01,  9.40889716e-02, -3.84685665e-01, -7.62421638e-02,
        2.70452145e-02,  1.13509304e-03,  1.61164179e-01,  2.20930010e-01,
        8.97680521e-02,  8.14433023e-02, -3.52856308e-01, -8.93854797e-02,
        3.13208774e-02,  3.17327917e-01, -5.73906861e-02,  3.04730027e-03,
        1.11116104e-01,  1.01184003e-01, -2.14633375e-01,  2.76519507e-01,
       -3.48517567e-01,  3.52829322e-02,  2.31731921e-01,  5.24204373e-01,
       -3.85801911e-01, -1.25550950e+00,  3.46757919e-01, -4.18438971e-01,
        8.28229859e-02,  3.68788302e-01,  5.05352259e-01, -3.11894685e-01,
       -2.80650854e-01,  5.48687875e-01, -6.80747509e-01, -1.59094900e-01,
        7.30119586e-01,  1.43466488e-01, -8.27392340e-02, -8.50622475e-01,
        4.00619507e-01,  2.69277364e-01, -4.39907074e-01, -3.03848177e-01,
        3.20879459e-01,  1.06679723e-01,  2.55969852e-01, -6.71665594e-02,
        3.20524280e-03,  2.37240821e-01,  3.48632634e-01, -3.85214388e-01,
        4.90312994e-01, -3.11777264e-01,  3.87561172e-01,  4.56366271e-01,
       -1.33560985e-01, -6.36327043e-02,  2.30831996e-01, -1.15221620e-01,
        6.03867173e-01, -5.53677738e-01,  7.43030086e-02, -3.47683817e-01,
        1.19060889e-01, -1.44318736e+00,  1.50213555e-01,  5.88119507e-01,
       -5.47617257e-01, -1.59976985e-02,  4.68391925e-01,  1.16399854e-01,
        1.82345688e-01,  2.51138628e-01,  6.07135057e-01, -1.51488289e-01,
       -4.22549456e-01, -4.75661233e-02,  2.38254204e-01,  7.16798067e-01,
       -9.32328105e-01,  4.65064263e-03,  2.69924283e-01,  1.02176212e-01,
       -3.28484446e-01, -5.05880475e-01, -1.08203128e-01, -1.10839859e-01,
        5.33260524e-01,  1.74619958e-01, -4.01156843e-01,  8.86539221e-02,
       -1.32927880e-01, -7.17068836e-02, -9.24904794e-02,  2.97947545e-02,
        1.75383672e-01,  2.14438990e-01,  8.16032439e-02, -3.29287231e-01,
        1.30626455e-01, -1.66535705e-01, -5.22108376e-01, -6.55278504e-01,
        5.66150963e-01,  4.57125269e-02, -4.14967000e-01, -7.43611753e-01,
        4.72704209e-02, -8.67617130e-01, -2.71104574e-01,  1.90545753e-01,
        4.08555627e-01, -6.24591336e-02,  3.49903047e-01,  2.96315938e-01,
       -7.33997881e-01, -4.87674326e-02, -6.35133311e-02, -5.76442838e-01,
       -6.77027404e-01,  3.96352828e-01,  6.16336660e-03,  2.93870687e-01,
       -1.20785050e-01, -7.55231604e-02, -9.90547612e-02,  2.13302016e-01,
        7.18903989e-02, -3.55855450e-02,  2.65714377e-01, -3.39241207e-01,
        2.74363220e-01, -4.26627249e-01,  2.09177077e-01,  7.19661266e-02,
       -2.36747429e-01, -8.27536210e-02, -3.26729752e-02, -1.66366562e-01,
       -3.73840839e-01,  3.63377273e-01,  3.88759226e-02, -7.63359591e-02,
        2.14802980e-01,  4.24972512e-02,  6.71085017e-03,  1.13314085e-01,
       -6.19720221e-01, -2.94147968e-01,  4.09931332e-01, -2.12011456e-01,
        3.65597308e-01, -2.72849023e-01,  6.53501928e-01, -7.94959009e-01,
       -3.59280974e-01, -6.64512515e-01, -2.73778409e-01,  1.85395032e-02,
       -2.17235863e-01,  4.21586726e-03, -1.50580332e-01, -3.79371718e-02,
       -6.18222915e-03, -2.06028357e-01, -5.32868981e-01,  5.49690366e-01,
       -3.73982817e-01, -4.47300971e-01, -4.39363003e-01, -3.10145438e-01,
        6.40785336e-01,  3.94642889e-01, -3.38466644e-01, -1.96477473e-02,
       -5.01787782e-01, -1.29666403e-01, -3.40673365e-02, -2.72158850e-02,
       -3.94998014e-01,  9.19549689e-02, -7.77505338e-02, -4.09228683e-01,
        1.27326936e-01, -8.60345513e-02,  3.83934289e-01,  1.11144006e-01,
       -6.05868502e-03,  6.00313544e-01, -2.07591072e-01, -8.67373869e-02,
       -6.21453166e-01, -2.65109450e-01,  1.57930240e-01,  4.16545838e-01,
       -6.25044480e-02, -1.36367783e-01,  3.58517826e-01, -2.80047685e-01,
        6.83490872e-01, -5.86977638e-02, -2.53277235e-02, -5.71726382e-01,
        2.65912712e-01,  3.59937012e-01, -4.64723468e-01,  1.84994876e-01,
        6.12208284e-02, -3.17198341e-03, -1.11002058e-01,  5.89758949e-03,
       -7.41466165e-01, -3.07093650e-01, -1.04904704e-01, -5.40950358e-01,
        4.85324144e-01, -2.07067519e-01, -7.08766341e-01,  5.82063422e-02,
       -1.50322214e-01, -4.84873980e-01, -2.47247323e-01, -3.35820675e-01,
       -4.97394681e-01, -1.91494644e-01,  2.92241555e-02,  2.77839303e-01,
       -1.50307280e-03,  2.00307772e-01, -6.95714235e-01,  8.88842046e-02,
        1.75379649e-01, -2.32660234e-01,  1.56216443e-01, -3.78527552e-01,
        1.31145269e-01,  2.57533163e-01, -5.31865917e-02, -9.62160155e-02,
        2.84838349e-01,  5.02256811e-01, -1.02728374e-01, -4.34132069e-01,
        3.30358624e-01, -7.01575652e-02, -2.19496772e-01, -3.55773829e-02,
        8.77896547e-01,  6.24395721e-03, -4.74945366e-01, -2.44224370e-01,
       -1.12394772e-01, -3.66993964e-01,  4.11569566e-01, -5.56115329e-01,
        4.99082983e-01,  3.00659865e-01,  5.41548550e-01, -8.95861089e-02,
       -3.86526376e-01,  4.40387651e-02, -1.94026187e-01,  2.25680694e-02,
       -2.63884366e-01, -3.09252143e-01, -9.78952348e-02, -1.19332843e-01,
        5.11524916e-01,  4.53795940e-01,  1.27526954e-01, -2.64159769e-01,
       -3.17193329e-01, -1.82853807e-02,  3.03743094e-01,  5.44688225e-01,
        3.82181555e-02, -1.96761042e-01,  2.89419651e-01, -4.01244074e-01,
       -6.37934878e-02,  9.18874443e-02, -3.83464038e-01, -2.46312842e-01,
        1.35341883e-01,  5.65760732e-01,  5.28354108e-01,  5.07210232e-02,
        1.31354645e-01, -2.09166571e-01,  1.28012210e-01,  2.91657865e-01,
        4.55007195e-01,  2.09910139e-01, -1.78564131e-01, -6.71462491e-02,
        6.37669384e-01, -2.04177395e-01, -2.11594760e-01, -5.89312553e-01,
       -1.58121064e-01, -4.71167594e-01,  1.06993131e-01,  2.47161668e-02,
        1.57782659e-01,  4.60270494e-01,  6.24035656e-01, -9.51524638e-03,
       -6.85671493e-02, -3.35049689e-01, -1.58582494e-01, -6.65803179e-02,
       -2.65061349e-01, -1.02169059e-01,  8.89373720e-01, -3.59511469e-03,
        2.88231373e-01,  6.73358962e-02,  5.30012846e-01, -3.66042882e-01,
       -1.07483506e-01, -5.96853316e-01, -3.72258484e-01,  6.10653684e-02,
       -5.06014585e-01, -5.45536280e-01, -6.30480230e-01, -4.17172492e-01,
       -1.18007116e-01, -4.21310186e-01, -3.94998521e-01,  5.03574871e-02,
       -1.51699945e-01,  2.09886596e-01, -3.05816764e-03,  3.51950049e-01,
       -3.96678984e-01,  1.65707171e-01, -5.21051705e-01,  5.67081988e-01,
        7.07143247e-02, -5.50841153e-01,  4.04556036e-01,  1.85697764e-01,
        2.68468112e-01, -5.91848791e-01,  2.33585089e-01, -7.79832065e-01,
       -1.37632877e-01, -2.76444137e-01,  5.96076017e-03, -7.99194813e-01,
        3.25124472e-01, -2.80637056e-01,  1.39286950e-01, -1.78333417e-01,
       -1.66058362e-01,  4.03724276e-02, -7.61653483e-01,  6.52021542e-02,
        1.69188827e-01,  1.56759676e-02,  1.79801062e-01, -1.30947009e-01,
        5.84469810e-02,  3.89080048e-01, -4.49709356e-01, -6.28283024e-01,
       -5.29901206e-01,  5.12068570e-02, -3.26781601e-01, -5.27595460e-01,
        8.82966071e-02,  8.75613332e-01, -7.73603693e-02,  3.03475590e-05,
       -6.91844344e-01,  1.02868848e-01,  4.35100347e-01, -7.46077359e-01,
       -7.30426088e-02,  8.16038549e-01, -6.85166776e-01, -6.24007694e-02,
        3.53185117e-01, -1.61174580e-01,  4.65094224e-02, -1.82974234e-01,
       -4.45524186e-01, -2.28713706e-01,  3.07288140e-01,  3.12445253e-01,
       -2.00655177e-01,  4.98717800e-02, -1.50747206e-02, -4.85529393e-01,
       -7.43270278e-01, -3.97631884e-01,  4.58114803e-01, -1.77064225e-01,
       -9.61046964e-02, -3.12499199e-02,  2.17697114e-01, -6.48826778e-01,
       -3.16706985e-01,  4.56436336e-01,  2.05361955e-02, -6.38957471e-02,
       -2.19017491e-01, -1.96405753e-01, -5.79461515e-01, -1.37959614e-01,
       -1.96385995e-01,  1.68938145e-01, -4.88003120e-02, -5.47457039e-01,
        4.08736080e-01, -1.95088442e-02,  2.26177201e-01, -4.81036663e-01,
       -3.36255580e-01, -1.72565728e-01,  5.78866228e-02, -6.89997315e-01,
       -9.48489606e-02, -9.66493040e-02,  1.31133363e-01, -3.82351041e-01,
        1.90744966e-01,  6.59849465e-01,  1.37413710e-01,  3.77266854e-01,
       -3.54470639e-03, -1.88506871e-01,  5.56465328e-01, -4.69488710e-01,
        1.11042611e-01,  2.21694827e-01, -7.99977183e-01,  3.51138860e-02,
        2.07477823e-01,  3.93626876e-02, -8.00674707e-02, -1.15947910e-01,
       -4.71977592e-01,  7.08483532e-02,  1.68094233e-01, -3.67015786e-02,
        4.40536618e-01, -1.97035491e-01,  4.22298729e-01, -2.10185632e-01,
        2.95074552e-01, -5.33307076e-01,  4.75517184e-01,  6.31803751e-01,
       -1.36246726e-01,  4.36614603e-01,  2.37735555e-01, -4.97074351e-02,
       -1.93025872e-01, -1.57721281e-01, -3.47057045e-01, -3.08906555e-01,
        1.36175245e-01,  5.80498934e-01,  6.84408545e-01,  9.87855718e-02,
       -1.49293378e-01,  5.17988801e-01, -6.66212618e-01,  1.11559249e-01,
       -4.73635465e-01,  9.04004425e-02, -6.70690775e-01, -6.67337626e-02,
       -5.25853336e-01,  1.87091962e-01, -2.59621888e-01,  4.36774381e-02,
       -8.24869633e-01, -2.55290151e-01,  2.20660359e-01,  1.19100340e-01,
       -4.27436233e-01, -2.97687054e-01, -4.77333367e-01, -2.84440964e-01,
       -1.61164820e-01, -9.26988348e-02,  3.92795831e-01, -4.06247348e-01,
        4.93895411e-01,  8.41352567e-02, -4.99464691e-01,  3.76094222e-01,
        1.85477853e-01, -3.13012481e-01,  2.52671987e-01,  3.97516966e-01,
       -5.79074502e-01, -2.37490892e-01,  3.53178233e-01, -1.82472803e-02,
        9.94464383e-02,  4.09008801e-01, -8.66513625e-02,  3.20055425e-01,
       -3.54808986e-01,  9.16681737e-02, -7.88684785e-01, -6.00100338e-01,
        6.07976951e-02, -1.65613502e-01, -6.32096455e-02,  1.21068932e-01,
       -1.60038099e-01, -3.94592106e-01, -7.35070825e-01,  4.42542881e-01,
        4.89969328e-02, -2.21790746e-02, -5.42330034e-02, -1.66791856e-01,
       -1.11494169e-01,  1.00177191e-02, -2.09427342e-01, -2.45768130e-01,
       -5.09527698e-02, -1.95012614e-01,  4.35706377e-01, -5.04015505e-01,
        6.19812869e-02,  1.21027909e-01, -8.03116262e-02, -1.04324870e-01,
        8.51777270e-02,  1.45401135e-02,  1.56938553e-01, -2.27790296e-01],
      dtype=float32)

In [ ]:
test_df["embedding"][100][100]

np.float32(-0.41012892)

In [ ]:
train_totall = train_totall.reset_index(drop=True)

In [ ]:
train_totall["merged_label"].value_counts()

merged_label
1    2838724
0     421526
3     317385
2      79313
4         63
Name: count, dtype: int64

In [ ]:
train_totall["embedding"][101]

array([-3.10099095e-01, -3.41315836e-01,  3.79133284e-01, -7.47476339e-01,
       -2.95149982e-01, -1.92298755e-01,  4.51870114e-01,  3.16165864e-01,
        1.00715065e+00,  3.79970223e-01,  2.56055653e-01, -8.46899897e-02,
       -1.06275275e-01,  2.24342346e-01, -1.15649179e-01, -9.74276382e-03,
       -1.09621979e-01, -1.95254266e-01, -2.13412002e-01, -8.07977676e-01,
        6.82970703e-01,  2.36354433e-02,  8.03704321e-01,  2.12491989e-01,
       -1.23257868e-01,  9.57263783e-02,  4.25049029e-02,  4.58052307e-02,
        3.52659106e-01,  4.28587086e-02, -1.20923758e-01, -4.39654291e-01,
       -2.28813410e-01,  2.86091000e-01,  4.93888676e-01, -8.62524379e-03,
       -3.61586183e-01, -3.19923908e-01,  5.34022488e-02, -2.62099266e-01,
       -3.61960202e-01,  8.96944180e-02,  1.41829342e-01,  2.15175539e-01,
        5.20456374e-01, -2.30521113e-01,  5.01014054e-01, -1.34681672e-01,
       -5.28817713e-01, -1.07301705e-01,  1.53642863e-01, -2.81239778e-01,
        1.31683901e-01,  2.12785780e-01, -1.58654690e-01, -1.87139228e-01,
        9.79504049e-01, -6.70133829e-02,  4.03542578e-01, -3.56557280e-01,
        2.21690029e-01, -1.03680238e-01, -1.66776717e-01,  1.08625434e-01,
       -1.13934755e-01,  2.09855139e-02,  4.66997698e-02,  5.20410955e-01,
       -6.20711625e-01, -2.68938839e-01,  1.25305176e+00,  5.50016165e-01,
        1.39752865e-01, -1.28726646e-01, -2.34396413e-01, -3.54268074e-01,
       -3.36407185e-01, -2.03542471e-01,  3.96274507e-01,  5.36650062e-01,
       -6.88717425e-01,  5.01372576e-01, -6.09347343e-01,  5.83725989e-01,
        2.36023888e-01, -9.20688510e-01, -5.50699770e-01,  1.28978446e-01,
       -1.50201738e-01, -1.06983697e-02, -4.07197922e-01, -2.30086073e-01,
        2.79347524e-02, -7.38263190e-01, -9.42758098e-02, -2.88949668e-01,
        3.41432869e-01, -2.59218633e-01,  1.00685251e+00,  4.80748713e-01,
       -8.09325948e-02, -7.50789702e-01, -2.38180727e-01,  5.03763378e-01,
       -3.46636832e-01,  1.87149942e-01,  1.52755352e-02,  2.81840265e-01,
        3.13488878e-02, -5.50278842e-01, -4.66885597e-01, -5.41656733e-01,
       -8.73871669e-02, -2.12335661e-02,  5.06657660e-01,  4.69466507e-01,
       -1.02005906e-01,  5.40509880e-01, -1.03603199e-01, -5.71226120e-01,
       -1.07865334e-01,  3.04683238e-01, -2.64896303e-01,  4.83780801e-01,
       -5.56793571e-01, -5.17370068e-02, -1.67252254e-02,  1.28603026e-01,
       -3.94429713e-02, -2.98530430e-01, -5.49755804e-02,  2.46251330e-01,
       -5.16530454e-01, -4.18768466e-01,  6.58615977e-02, -1.48923010e-01,
        2.00302795e-01, -1.20860934e-01,  1.31204203e-01, -3.86695176e-01,
        1.75842568e-01,  1.77465409e-01,  2.65446659e-02,  2.97241598e-01,
        1.31121382e-01,  3.65201980e-01, -3.99906665e-01,  9.01785046e-02,
       -4.99993712e-01, -6.70104384e-01, -3.73850256e-01,  3.21355432e-01,
        1.37617931e-01,  4.66324419e-01, -7.04524457e-01,  1.57980636e-01,
        6.02217436e-01, -4.05466497e-01,  2.74597436e-01, -3.81068408e-01,
       -2.36027747e-01,  3.54468226e-02,  5.97495079e-01, -1.57112807e-01,
       -4.78826970e-01,  9.25778687e-01,  8.78548399e-02,  2.79871732e-01,
        6.00349642e-02,  3.61952633e-02, -4.61466223e-01, -1.93887368e-01,
       -4.66023564e-01, -9.03625488e-02,  3.31905961e-01,  4.91222948e-01,
        1.27685234e-01,  5.58543324e-01, -1.68649927e-01, -4.80515748e-01,
        3.57063115e-01,  4.43146765e-01,  4.78943139e-01,  3.29522729e-01,
        2.18469992e-01,  4.51355815e-01, -6.26012683e-01,  6.22671731e-02,
       -3.54713798e-01,  2.05489993e-02, -4.12586719e-01,  2.96535671e-01,
        4.14993346e-01, -5.45715511e-01,  3.76967750e-02, -9.17999893e-02,
       -2.33419891e-02, -1.29226696e+00, -2.00756699e-01, -4.40475583e-01,
        3.36324632e-01, -3.60139310e-01,  4.35191780e-01, -4.95309569e-02,
        1.76843807e-01, -1.51728600e-01, -6.28023446e-02, -3.54647666e-01,
       -7.50324577e-02, -4.04416054e-01, -9.20292556e-01,  7.66252458e-01,
        2.06135809e-01,  4.57044780e-01, -7.28971243e-01, -2.72275172e-02,
       -3.52753490e-01,  6.20419502e-01,  1.87896520e-01,  1.24077588e-01,
       -2.42521748e-01, -2.08681896e-01,  2.56015331e-01, -2.98543721e-01,
       -1.78551480e-01, -6.13756515e-02,  5.62563896e-01,  4.46333557e-01,
       -2.57671485e-03, -1.53257772e-01, -1.88652560e-01,  1.15852289e-01,
        6.92322925e-02, -5.16342103e-01, -3.23819697e-01, -5.76222735e-03,
       -2.66654994e-02, -4.57442313e-01,  8.65716279e-01, -2.29820341e-01,
        2.17462763e-01,  1.21098064e-01, -5.09132594e-02, -1.19061582e-01,
       -8.44740048e-02,  6.08943701e-02, -2.00416833e-01,  4.70572352e-01,
        4.83589098e-02, -4.05627042e-01,  5.91026664e-01,  2.31966272e-01,
       -5.68313062e-01, -1.82895467e-01,  3.66231263e-01,  2.23336175e-01,
        2.34876871e-01,  3.52863103e-01,  2.17781276e-01,  2.50024498e-01,
       -2.92023033e-01, -5.58703363e-01, -3.88966352e-01, -4.35870796e-01,
       -2.58396178e-01, -1.66750997e-01,  1.31486863e-01, -6.73308551e-01,
        5.48046708e-01,  5.21845937e-01, -3.37032825e-01,  3.12596053e-01,
        4.29412693e-01, -8.99359643e-01,  6.77538335e-01,  1.24291137e-01,
       -1.47955492e-01, -2.26095498e-01,  2.03420877e-01,  3.85928631e-01,
       -1.37733921e-01, -3.23771834e-01,  3.82117815e-02, -3.95064831e-01,
       -1.02740144e-02, -4.65823337e-02, -3.68240982e-01, -5.69586217e-01,
       -3.15549731e-01, -1.94965646e-01,  2.46103302e-01, -4.09545481e-01,
       -2.00648606e-01, -1.24326348e+00, -3.22398812e-01,  1.28901452e-01,
        2.50978372e-03,  6.55701220e-01,  5.90199769e-01, -6.84880257e-01,
       -4.97418731e-01,  4.23762023e-01, -8.60355273e-02,  8.13115761e-02,
        1.74254514e-02, -2.14013830e-01, -1.19841859e-01, -9.56934318e-02,
       -3.18905830e-01,  5.23027241e-01,  1.97951853e-01, -8.82803679e-01,
        4.71968383e-01, -3.00181121e-01,  1.18069164e-01, -7.79189944e-01,
       -7.44050741e-01, -7.58383051e-02, -5.60043097e-01, -4.41570282e-01,
        3.86304528e-01, -2.42514923e-01,  1.02306686e-01,  1.36304155e-01,
        2.78484613e-01,  9.61808860e-02, -4.52288955e-01, -3.76299769e-01,
        1.61247537e-01,  3.80409181e-01, -6.70643508e-01, -3.29341531e-01,
        3.98814194e-02,  2.89426863e-01,  6.17657065e-01, -7.16939330e-01,
       -3.60808253e-01, -1.03306365e+00, -6.52120471e-01, -2.71080911e-01,
       -7.83811361e-02, -1.33415997e-01, -1.16093147e+00,  1.24757051e-01,
        1.34579077e-01,  4.70826775e-01,  9.74801257e-02,  1.41665548e-01,
       -3.28844249e-01,  4.71874082e-04,  4.84605283e-01, -7.36544788e-01,
       -3.51024896e-01, -2.96992630e-01,  3.22809398e-01, -3.74402940e-01,
        4.88202661e-01,  6.67602181e-01, -3.32366437e-01,  1.96736246e-01,
       -7.04531968e-01,  6.74641013e-01,  4.41424340e-01,  4.05476242e-01,
        4.06715602e-01, -9.28655043e-02,  8.51998478e-02,  6.99260160e-02,
       -2.36041710e-01, -2.25671336e-01,  2.96831638e-01, -1.30425110e-01,
       -1.37559474e-01, -6.34641469e-01, -3.01139921e-01, -5.23497403e-01,
        7.68994749e-01, -2.26289436e-01, -1.50210649e-01, -6.76548064e-01,
        5.04158139e-01,  5.01136899e-01,  1.03510261e-01, -5.89256465e-01,
       -3.05013716e-01, -2.72575878e-02, -2.62019187e-01,  1.74007043e-01,
       -1.48790225e-01,  5.15663624e-01, -2.00663935e-02, -4.87488061e-01,
       -5.80317199e-01,  8.63880962e-02,  9.33698639e-02,  1.82969823e-01,
       -1.05067059e-01, -1.87843159e-01, -6.70792162e-01,  1.28589436e-01,
       -4.70097095e-01, -4.35108215e-01, -4.05787796e-01, -2.18218669e-01,
       -3.11881661e-01, -1.03220223e-02,  1.53875321e-01, -4.32351440e-01,
        2.65752375e-02, -1.65540621e-01, -5.54933786e-01,  2.29049683e-01,
        8.18105191e-02, -3.23908001e-01,  4.74870764e-02, -2.80291826e-01,
        2.26919264e-01,  5.05545914e-01, -6.85608611e-02,  6.68967590e-02,
       -4.02821526e-02, -2.93484747e-01,  4.13384110e-01,  1.66742932e-02,
        6.15736961e-01,  5.68716943e-01, -1.24490680e-02, -2.35019684e-01,
       -1.19702466e-01, -7.75298536e-01, -5.54910481e-01,  1.80209801e-01,
        4.60427970e-01,  1.53396979e-01, -1.74072382e-04, -3.01703304e-01,
        2.12889507e-01, -2.08708659e-01,  3.62737536e-01, -4.57992405e-02,
       -3.52239728e-01, -1.82098255e-01,  8.36256146e-01, -2.05577672e-01,
       -4.41331863e-01,  1.26134112e-01, -3.10262829e-01,  3.45389903e-01,
       -2.58920580e-01, -3.60129327e-01, -3.41765225e-01,  7.20803440e-02,
        3.31425011e-01, -3.94569725e-01, -4.13941503e-01,  7.15510666e-01,
       -4.01329428e-01,  3.11719269e-01, -1.15268564e+00,  2.11311117e-01,
        4.85276571e-03, -5.62481463e-01, -3.22799291e-03, -5.15060842e-01,
        5.42384565e-01,  7.65682831e-02,  9.38167945e-02,  5.06009996e-01,
       -1.97633803e-01,  2.46116772e-01, -4.14278030e-01, -9.53378975e-02,
        3.05726558e-01, -8.40479210e-02, -2.56966464e-02, -8.42277169e-01,
       -9.79003012e-02, -9.09686506e-01, -8.94066215e-01, -2.78878748e-01,
       -2.41904095e-01, -2.69020289e-01,  6.69910967e-01, -8.14694643e-01,
        1.10811204e-01, -3.04544359e-01,  7.13023990e-02,  3.48559827e-01,
        9.05213058e-02, -1.80329755e-01,  2.87157387e-01,  4.74347770e-01,
        3.38202953e-01, -2.20162217e-02,  2.80443072e-01,  9.45815682e-01,
        9.38443746e-03,  6.18059099e-01, -3.97411324e-02, -4.44310844e-01,
       -1.07975411e+00, -1.36898518e-01, -3.50485653e-01,  2.21788734e-01,
        8.15442726e-02,  9.93125677e-01,  1.56971455e-01, -5.13880432e-01,
        1.69102773e-01, -6.67043805e-01,  6.19321801e-02,  4.28289413e-01,
        9.83420730e-01, -1.51604593e-01,  3.86543095e-01,  1.09101869e-01,
       -3.17024529e-01, -7.47842610e-01,  1.86102420e-01,  2.22728968e-01,
       -2.56940305e-01,  8.01130105e-03,  4.53756422e-01, -2.27299556e-01,
        3.70910764e-01,  1.38282860e-02, -1.45887181e-01,  4.94567957e-03,
       -4.20488060e-01, -5.57208300e-01, -1.51886851e-01,  6.03479482e-02,
        6.98492005e-02, -1.14892697e+00,  8.36682498e-01, -2.16298908e-01,
       -8.51148292e-02, -9.86702740e-02, -2.96858281e-01, -2.12064728e-01,
        6.71215832e-01, -3.60986769e-01,  1.05964378e-01, -8.85069907e-01,
       -1.07862361e-01,  5.57737887e-01,  3.16077679e-01,  4.26909268e-01,
        5.56081891e-01, -4.15124625e-01, -7.82519579e-02,  2.66790092e-01,
        2.61391461e-01, -1.19723193e-01,  3.34096640e-01,  8.61852318e-02,
       -3.35072167e-02, -3.48196477e-01, -2.11571872e-01, -1.94459304e-01,
       -4.56479937e-02,  4.54538465e-01,  1.23217538e-01, -1.54968882e-02,
        1.06713510e+00,  1.25367999e-01,  1.28244072e-01, -4.01803583e-01,
       -1.27976134e-01, -5.72400749e-01, -6.67590797e-01, -3.83416235e-01,
        2.47355044e-01, -7.39965022e-01,  1.88545644e-01, -9.96686995e-01,
       -7.64736056e-01,  9.32407938e-03, -8.40106010e-02, -5.20631671e-01,
        3.48490536e-01,  2.67780721e-01, -5.21425068e-01, -6.68471977e-02,
        1.04890776e+00,  3.62515926e-01,  7.83120617e-02, -2.72235423e-01,
        4.18799669e-01, -7.48895466e-01, -3.75181526e-01,  1.67881563e-01,
        2.83993393e-01,  6.61138445e-02, -3.91626388e-01, -2.90724248e-01,
       -3.87041122e-02,  2.59784132e-01,  5.83336502e-02, -3.90849531e-01,
       -1.07882649e-01, -1.13317125e-01, -5.18399656e-01,  7.57011294e-01,
       -4.87167090e-01, -2.25006998e-01,  6.48433387e-01, -8.24831665e-01,
       -1.14933014e-01,  9.63833511e-01, -1.45695940e-01, -4.64310139e-01,
       -2.64762670e-01, -1.08715475e+00, -1.06598675e+00, -3.64458591e-01,
        5.67798018e-02,  1.17095061e-01, -1.62110813e-02,  1.56527326e-01,
        3.06105733e-01,  2.30726942e-01, -2.85531491e-01, -1.49038479e-01,
       -7.73229152e-02,  2.15105284e-02,  1.05455993e-02, -3.53493631e-01,
       -6.45968735e-01, -6.62943274e-02, -3.92202020e-01,  5.25826998e-02,
        2.33774155e-01,  2.25047499e-01,  2.29114562e-01, -6.33505657e-02,
        3.77001345e-01,  1.06887314e-02, -9.35033202e-01, -1.00276254e-01,
        5.29558063e-01, -1.33452579e-01,  1.95481330e-01, -2.53028959e-01,
        4.31257933e-01, -5.78812182e-01, -3.26614082e-01, -3.09261858e-01,
        2.47724533e-01,  1.68751568e-01, -8.48132730e-01, -3.17830667e-02,
       -2.45885566e-01, -1.32230937e-01,  4.60529119e-01, -3.74486446e-02,
        3.25286925e-01,  5.21986365e-01,  3.81190449e-01, -4.03360486e-01,
        2.56106239e-02,  3.35005298e-02,  4.78253394e-01,  1.83159888e-01,
        2.25857824e-01,  5.68071365e-01, -1.07290678e-01,  7.39089668e-01,
       -1.62429407e-01, -6.35295272e-01,  1.98805526e-01, -3.10988784e-01,
       -6.73448145e-01, -1.89868268e-02,  1.93177953e-01,  5.22781312e-01,
        7.02539206e-01,  2.54148513e-01,  1.32829130e-01, -1.03922296e+00,
        2.74312347e-01, -1.09904848e-01,  7.19993234e-01,  8.17665219e-01,
       -4.11717027e-01,  1.57211736e-01,  1.72210768e-01,  2.50101201e-02,
       -6.25609636e-01, -6.05208635e-01, -2.34810159e-01, -3.57459188e-01,
        3.15067381e-01, -1.83301389e-01,  5.32421410e-01,  2.75572270e-01,
        8.49739164e-02,  3.60102832e-01,  1.00166708e-01,  2.05101833e-01,
        1.24399340e+00,  1.04775224e-02, -2.40704387e-01, -2.39837691e-02,
       -1.29206970e-01,  2.99269080e-01, -9.35200825e-02,  9.98255834e-02,
       -2.43763700e-01, -1.89837396e-01, -1.74446572e-02,  7.41456971e-02,
       -3.52060884e-01,  2.94726998e-01,  2.22900227e-01,  5.96560026e-03,
       -6.19614199e-02, -1.64944187e-01,  7.34572351e-01, -4.66081202e-01,
       -2.27491945e-01,  4.02727306e-01, -5.31422079e-01, -5.27806222e-01,
        6.92683235e-02, -1.25074133e-01, -4.54242140e-01,  4.70422447e-01,
       -5.13072670e-01,  2.23086700e-01,  2.69030213e-01, -1.54327095e-01,
        2.75572985e-01,  1.22807041e-01,  2.10800439e-01,  1.16289467e-01,
        3.33674178e-02,  1.37850568e-01, -1.49909558e-03, -9.63952690e-02,
        8.78228173e-02,  3.48284543e-01,  3.70783210e-01, -2.94887036e-01,
        1.44048721e-01, -6.89701080e-01, -2.76246250e-01, -3.72767225e-02,
       -9.60751027e-02,  4.01408941e-01, -4.56926823e-01,  3.17060113e-01,
       -3.22373450e-01,  2.65929610e-01,  6.55113637e-01,  4.14300144e-01,
       -3.38263422e-01, -6.70240447e-02,  4.38209057e-01,  5.12363255e-01,
        6.65294975e-02,  2.90676594e-01, -4.33695525e-01, -3.33050042e-01,
        2.02009574e-01, -2.59504676e-01,  7.90593401e-02, -7.17622221e-01],
      dtype=float32)

In [ ]:
X_batch = model.encode(train_totall["sentence"][101], show_progress_bar=False)

In [ ]:
np.array_equal(train_totall["embedding"][101] , X_batch)

False

In [ ]:
X_batch[100]

np.float32(-0.31009915)

In [ ]:
train_totall["embedding"][101][100]

np.float32(-0.080932595)

## 오버샘플링/임베딩
-> 다운샘플링/임베딩
GPU 크기가 너무 많이 듣다.

###다운샘플링
- 1에 맞춰서 다운샘플링하기

In [ ]:
import pandas as pd
from sklearn.utils import resample

# 예: df는 'text'와 'label' 컬럼이 있는 DataFrame
# df = pd.read_csv("your_data.csv")

# 각 라벨의 샘플 수 확인
label_counts = Totall_Data['label'].value_counts()
min_count = 838724  # 가장 적은 수를 기준으로 다운샘플링(1기준)

# 라벨별 다운샘플링
balanced_data = []

for label in label_counts.index:
    subset = Totall_Data[Totall_Data['mer'] == label]
    downsampled = resample(subset,
                           replace=False,
                           n_samples=min_count,
                           random_state=42)
    balanced_data.append(downsampled)

# 결합 및 셔플
balanced_df = pd.concat(balanced_data)
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

ValueError: Cannot sample 838724 out of arrays with dim 421352 when replace is False

###텍스트 다운로드

In [ ]:
import pandas as pd

# 예시: label 컬럼이 있는 DataFrame
# df = pd.read_csv(...) 또는 pd.read_parquet(...)

# 라벨 1만 샘플링
label_1_sample = Totall_Data[Totall_Data['merged_label'] == 1].sample(n=538724, random_state=42)

# 라벨 0, 2, 3, 4는 전부 다 사용
other_labels = Totall_Data[Totall_Data['merged_label'] != 1]

# 결합
downsampled_df = pd.concat([label_1_sample, other_labels]).reset_index(drop=True)

In [ ]:
downsampled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1357011 entries, 0 to 1357010
Data columns (total 7 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Unnamed: 0    1357011 non-null  int64
 1   sentence      1357011 non-null  object
 2   doc_id        1357011 non-null  int64
 3   sentence_idx  1357011 non-null  int64
 4   label         1357011 non-null  int64
 5   merged_label  1357011 non-null  int64
 6   embedding     1357011 non-null  object
dtypes: int64(5), object(2)
memory usage: 72.5+ MB

In [ ]:
downsampled_df["merged_label"].value_counts()

merged_label
1    538724
0    421526
3    317385
2     79313
4        63
Name: count, dtype: int64

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import random
downsampled_df = pd.read_parquet("/content/drive/MyDrive/DataSet/샘플링_최종_훈련셋/train_totall_set.parquet")

In [2]:
downsampled_df_train = downsampled_df.drop(['sentence', 'label'], axis=1)

###오버샘플링
-> GPU에 과해서 포기

In [ ]:
from imblearn.over_sampling import SMOTE, RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sentence_transformers import SentenceTransformer

# 2. 오버샘플링
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X, y)

# 3. 원본 메타정보 추적을 위해 인덱스도 가져옴
resampled_idx = ros.sample_indices_
train_df_resampled = train_df.iloc[resampled_idx].copy()
train_df_resampled['embedding'] = list(X_resampled)
train_df_resampled['label'] = y_resampled

####데이터 로드/저장

테이터 저장

In [ ]:
train_df_resampled.to_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet", index=False)

In [ ]:
train_df_resampled = pd.read_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet")

In [ ]:
embeddings = train_df_resampled['embedding']
np.save('/content/drive/MyDrive/DataSet/suffled_sample/embedding_X.npy', embeddings)
train_df_resampled.drop(columns='embedding').to_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet", index=False)

In [ ]:
train_df_resampled.drop(columns='embedding').to_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet", index=False)

데이터 불러오기

In [ ]:
train_df_resampled = pd.read_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet")
embeddings = np.load('/content/drive/MyDrive/DataSet/suffled_sample/embedding_X.npy', allow_pickle=True)
train_df_resampled["embedding"] = list(embeddings)

In [ ]:
#train_df_resampled = pd.read_parquet("/content/drive/MyDrive/DataSet/suffled_sample/embedding_ko-sroberta.parquet")
embeddings = np.load('/content/drive/MyDrive/DataSet/suffled_sample/embedding_X.npy', allow_pickle=True)
train_df_resampled["embedding"] = list(embeddings)

## attention모듈 모델 학습 및 평가

In [ ]:
import gc, torch

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

## 모델 적용

In [3]:
downsampled_df_train["merged_label"].value_counts()

merged_label
1    538724
0    421526
3    317385
2     79313
4        63
Name: count, dtype: int64

In [4]:
downsampled_df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1357011 entries, 0 to 1357010
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Unnamed: 0    1357011 non-null  int64
 1   doc_id        1357011 non-null  int64
 2   sentence_idx  1357011 non-null  int64
 3   merged_label  1357011 non-null  int64
 4   embedding     1357011 non-null  object
dtypes: int64(4), object(1)
memory usage: 51.8+ MB

In [5]:
print("라벨 분포 확인:", downsampled_df_train['merged_label'].value_counts())
print("최소/최대 라벨:", downsampled_df_train['merged_label'].min(), downsampled_df_train['merged_label'].max())

라벨 분포 확인: merged_label
1    538724
0    421526
3    317385
2     79313
4        63
Name: count, dtype: int64
최소/최대 라벨: 0 4

In [12]:
# ------------------------------
# 필수 라이브러리 불러오기
# ------------------------------
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.model_selection import StratifiedKFold
from torch.cuda.amp import GradScaler # ✅ 수정됨: autocast는 torch.amp에서 직접 사용
import gc
import os # os.cpu_count() 사용을 위해 추가
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

# ------------------------------
# Dataset 클래스
# ------------------------------
class DocumentAwareDataset(Dataset):
    def __init__(self, df):
        self.all_inputs = []
        self.all_labels = []
        self.doc_indexes = []

        # doc_id를 0부터 시작하는 정수 인덱스로 매핑
        unique_doc_ids = df['doc_id'].unique()
        doc_id_map = {doc_id: idx for idx, doc_id in enumerate(unique_doc_ids)}

        for doc_id, group in df.groupby("doc_id"):
            embeddings = np.stack(group['embedding'].values)  # [N, 768] - 사전 계산된 임베딩 사용
            sentence_ids = group['sentence_idx'].values.astype(np.float32)
            labels = group['merged_label'].values.astype(np.int64)

            # 문장 인덱스 정규화 (문서 내 상대적 위치)
            sentence_ids -= sentence_ids.min()
            max_val = sentence_ids.max()
            if len(sentence_ids) > 1 and max_val > 0:
                sentence_ids = sentence_ids / max_val
            else:
                sentence_ids = np.zeros_like(sentence_ids)

            positions = sentence_ids[:, np.newaxis]
            inputs = np.concatenate([embeddings, positions], axis=1) # 임베딩(768) + 위치정보(1) = 769

            doc_index = doc_id_map[doc_id] # 매핑된 정수 인덱스 사용
            for i in range(len(inputs)):
                self.all_inputs.append(inputs[i])
                self.all_labels.append(labels[i])
                self.doc_indexes.append(doc_index)

        self.all_inputs = torch.tensor(np.array(self.all_inputs), dtype=torch.float32)
        self.all_labels = torch.tensor(np.array(self.all_labels), dtype=torch.long)
        self.doc_indexes = torch.tensor(np.array(self.doc_indexes), dtype=torch.long)

    def __len__(self):
        return len(self.all_labels)

    def __getitem__(self, idx):
        return self.all_inputs[idx], self.all_labels[idx], self.doc_indexes[idx]

# ------------------------------
# 모델 정의
# ------------------------------
class AttentiveHierarchicalClassifier(nn.Module):
    def __init__(self, input_dim=769, hidden_dim=256, num_classes=5): # input_dim은 임베딩(768) + 위치(1)
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.LayerNorm(hidden_dim),
        )

        self.attn_doc = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        self.attn_global = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.Tanh(),
            nn.Linear(128, 1)
        )

        self.classifier = nn.Linear(hidden_dim * 3, num_classes)

    # ✅ 수정됨: AttributeError 해결을 위해 forward 함수 전체 로직 수정
    def forward(self, x, doc_mask):
        h = self.encoder(x)

        doc_context = torch.zeros_like(h)
        # 배치 내 각 문서에 대한 컨텍스트 계산
        for doc_id_val in torch.unique(doc_mask):
            # nonzero()의 결과는 튜플이므로, 첫 번째 요소를 사용해야 합니다.
            indices_tuple = (doc_mask == doc_id_val).nonzero(as_tuple=True)

            # 튜플의 첫 번째 요소(텐서)에 대해 numel()을 호출하여 요소가 있는지 확인합니다.
            if indices_tuple[0].numel() == 0:
                continue

            # 실제 인덱스 텐서를 가져옵니다.
            doc_indices = indices_tuple[0]

            doc_h = h[doc_indices]
            weights = torch.softmax(self.attn_doc(doc_h).squeeze(-1), dim=0)
            weighted = torch.sum(doc_h * weights.unsqueeze(-1), dim=0, keepdim=True)

            # 실제 인덱스 텐서로 컨텍스트를 할당하고, expand 크기도 실제 인덱스 개수를 사용합니다.
            doc_context[doc_indices] = weighted.expand(doc_indices.size(0), -1)

        global_weights = torch.softmax(self.attn_global(h).squeeze(-1), dim=0)
        global_context = torch.sum(h * global_weights.unsqueeze(-1), dim=0, keepdim=True)
        expanded_global = global_context.expand(h.size(0), -1)

        concat = torch.cat([h, doc_context, expanded_global], dim=1)
        logits = self.classifier(concat)
        return logits

# ------------------------------
# 학습 및 평가 함수 + 최고 성능 모델 저장
# ------------------------------
def cross_validate_model(df, n_splits=3, epochs=3, batch_size=128, lr=5e-4):
    X = df.index.values # StratifiedKFold는 인덱스를 사용하도록 변경
    y = df['merged_label'].values
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

    all_preds, all_labels_gold = [], []
    best_f1 = -1

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"✅ 현재 사용 중인 디바이스: {device}")
    if torch.cuda.is_available():
        print(f"🛠️ GPU 이름: {torch.cuda.get_device_name(0)}")
        print(f"🔥 초기 GPU 메모리 사용량: {torch.cuda.memory_allocated(device) / 1024**2:.2f} MB")

    available_cpus = os.cpu_count()
    num_workers = min(4, available_cpus if available_cpus is not None else 1)
    print(f"🔩 DataLoader num_workers: {num_workers}")


    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        print(f"\n🚀 Fold {fold+1}/{n_splits}")
        train_df = df.iloc[train_idx].reset_index(drop=True)
        val_df = df.iloc[val_idx].reset_index(drop=True)

        train_dataset = DocumentAwareDataset(train_df)
        val_dataset = DocumentAwareDataset(val_df)

        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                                  num_workers=num_workers, pin_memory=True if device.type == 'cuda' else False,
                                  persistent_workers=True if num_workers > 0 and hasattr(DataLoader, 'persistent_workers') else False,
                                  drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False,
                                num_workers=num_workers, pin_memory=True if device.type == 'cuda' else False,
                                persistent_workers=True if num_workers > 0 and hasattr(DataLoader, 'persistent_workers') else False)

        model = AttentiveHierarchicalClassifier(num_classes=df['merged_label'].nunique()).to(device)

        if hasattr(torch, 'compile') and device.type == 'cuda':
            print("✅ torch.compile을 사용하여 모델 컴파일 중...")
            try:
                model = torch.compile(model, mode="reduce-overhead")
                print("✅ 모델 컴파일 완료.")
            except Exception as e:
                print(f"⚠️ torch.compile 실패: {e}. 기본 모델로 진행합니다.")

        class_counts = torch.bincount(train_dataset.all_labels)
        epsilon = 1e-6
        class_weights = 1. / (class_counts.float() + epsilon)
        print(f"⚖️ 클래스 가중치: {class_weights}")

        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
        scaler = GradScaler(enabled=device.type == 'cuda')

        model.train()
        for epoch in range(epochs):
            total_loss = 0
            for step, (xb, yb, docb) in enumerate(train_loader):
                xb, yb, docb = xb.to(device), yb.to(device), docb.to(device)

                optimizer.zero_grad(set_to_none=True)

                # ✅ 수정됨: 최신 PyTorch 버전에 맞는 autocast 사용법으로 변경
                with torch.amp.autocast(device_type=device.type, dtype=torch.float16, enabled=(device.type == 'cuda')):
                    logits = model(xb, docb)
                    loss = criterion(logits, yb)

                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

                total_loss += loss.item()
            print(f"  Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(train_loader):.4f}")

        model.eval()
        fold_preds, fold_labels_gold = [], []
        with torch.no_grad():
            for xb, yb, docb in val_loader:
                xb, yb, docb = xb.to(device), yb.to(device), docb.to(device)

                # ✅ 수정됨: 최신 PyTorch 버전에 맞는 autocast 사용법으로 변경
                with torch.amp.autocast(device_type=device.type, dtype=torch.float16, enabled=(device.type == 'cuda')):
                    logits = model(xb, docb)
                preds = torch.argmax(logits, dim=1)
                fold_preds.extend(preds.cpu().numpy())
                fold_labels_gold.extend(yb.cpu().numpy())

        fold_f1 = f1_score(fold_labels_gold, fold_preds, average='macro', zero_division=0)
        print(f"  🎯 Fold {fold+1} Macro-F1: {fold_f1:.4f}")

        if fold_f1 > best_f1:
            best_f1 = fold_f1
            # 컴파일된 모델의 state_dict를 저장하려면 아래와 같이 처리할 수 있습니다.
            # model_state = model._orig_mod.state_dict() if hasattr(model, '_orig_mod') else model.state_dict()
            torch.save(model.state_dict(), 'best_model.pt')
            print("  💾 Best model saved as 'best_model.pt'")

        all_preds.extend(fold_preds)
        all_labels_gold.extend(fold_labels_gold)

        del model, train_loader, val_loader, train_dataset, val_dataset, optimizer, criterion, class_weights
        gc.collect()
        if device.type == 'cuda':
            torch.cuda.empty_cache()
            print(f"🔥 Fold 종료 후 GPU 메모리 사용량: {torch.cuda.memory_allocated(device) / 1024**2:.2f} MB")

    acc = accuracy_score(all_labels_gold, all_preds)
    final_f1 = f1_score(all_labels_gold, all_preds, average='macro', zero_division=0)
    print(f"\n✅ Cross-Validation Accuracy: {acc:.4f}, Macro-F1: {final_f1:.4f}")
    print("🎉 Best Fold Macro-F1: {:.4f}".format(best_f1))
    print("📦 Saved best model to: best_model.pt")

    print("\n📋 최종 분류 리포트:")
    print(classification_report(all_labels_gold, all_preds, zero_division=0))

In [13]:
cross_validate_model(downsampled_df_train, n_splits=2, epochs=5, batch_size=4098, lr=1e-4)

✅ 현재 사용 중인 디바이스: cuda
🛠️ GPU 이름: NVIDIA A100-SXM4-40GB
🔥 초기 GPU 메모리 사용량: 29.19 MB
🔩 DataLoader num_workers: 4

🚀 Fold 1/2
✅ torch.compile을 사용하여 모델 컴파일 중...
✅ 모델 컴파일 완료.
⚖️ 클래스 가중치: tensor([4.7447e-06, 3.7125e-06, 2.5216e-05, 6.3015e-06, 3.2258e-02])

<ipython-input-12-1541135362>:176: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=device.type == 'cuda')

  Epoch 1/2 | Loss: 0.6790
  Epoch 2/2 | Loss: 0.3714
  🎯 Fold 1 Macro-F1: 0.6493
  💾 Best model saved as 'best_model.pt'
🔥 Fold 종료 후 GPU 메모리 사용량: 29.49 MB

🚀 Fold 2/2
✅ torch.compile을 사용하여 모델 컴파일 중...
✅ 모델 컴파일 완료.
⚖️ 클래스 가중치: tensor([4.7447e-06, 3.7125e-06, 2.5217e-05, 6.3015e-06, 3.1250e-02])

<ipython-input-12-1541135362>:176: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=device.type == 'cuda')

  Epoch 1/2 | Loss: 0.6481
  Epoch 2/2 | Loss: 0.3639
  🎯 Fold 2 Macro-F1: 0.6453
🔥 Fold 종료 후 GPU 메모리 사용량: 29.49 MB

✅ Cross-Validation Accuracy: 0.8485, Macro-F1: 0.6473
🎉 Best Fold Macro-F1: 0.6493
📦 Saved best model to: best_model.pt

📋 최종 분류 리포트:
              precision    recall  f1-score   support

           0       0.98      0.95      0.97    421526
           1       0.96      0.68      0.80    538724
           2       0.41      0.96      0.57     79313
           3       0.83      0.96      0.89    317385
           4       0.00      0.65      0.01        63

    accuracy                           0.85   1357011
   macro avg       0.64      0.84      0.65   1357011
weighted avg       0.90      0.85      0.86   1357011